accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('search-movie/', views.search_movie, name='search_movie'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like')

]

fluffyhappiness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('about/',  TemplateView.as_view(template_name="about.html"), name='about'),
    path('', views.home, name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('search-movie/', views.search_movie, name='search_movie'),
    path('api-movie/', views.api_movie),
    path('api-genre/', views.api_genre),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comments/create/', views.create_moviecomment, name='create_moviecomment'),
    path('<int:movie_pk>/watch/', views.watch, name='watch'),
]

community/models.py
from django.db import models
from movies.models import Movie
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.

class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rank = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')


class ReviewComment(models.Model):
    content = models.TextField()
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

community/forms.py
from django import forms
from .models import Review, ReviewComment
from .widgets import AutoCompleteWidget, starWidget

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['title', 'movie_title', 'rank', 'content']
        widgets = {
            'rank': starWidget,
        }


class ReviewCommentForm(forms.ModelForm):

    class Meta:
        model = ReviewComment
        exclude = ['review', 'user']

community/views.py
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Review
from .forms import ReviewForm, ReviewCommentForm
from movies.models import Movie
from django.core import serializers
from django.forms.models import model_to_dict
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

@require_GET
def index(request):
    reviews = Review.objects.all()
    paginator = Paginator(reviews, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'reviews': page_obj,
    }

    return render(request, 'community/index.html', context)

@require_http_methods(['GET', 'POST'])
@login_required
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)

    else:
        form = ReviewForm()

    context = {
        'form': form
    }
    return render(request, 'community/create.html', context)


@require_GET
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.reviewcomment_set.all()
    comment_form = ReviewCommentForm()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments
    }

    return render(request, 'community/detail.html', context)


@require_http_methods(['GET', 'POST'])
@login_required
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)

    if request.user != review.user:
        return redirect('community:detail', review_pk)

    
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('community:detail', review.pk)

    else:
        form = ReviewForm(instance=review)

    context = {
        'form': form,
        'review': review
    }

    return render(request, 'community/create.html', context)


@require_POST
def delete(request, review_pk):
    if request.method == "POST":
        review = get_object_or_404(Review, pk=review_pk)
    
        if request.user == review.user:
            review.delete()
            return redirect('community:index')
    
    return redirect('community:detail', review_pk)



@require_POST
@login_required
def create_comment(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form = ReviewCommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review = review
            comment.user = request.user
            comment.save()
            cnt= len(review.reviewcomment_set.all())

            context = {
                'username': request.user.username,
                'content': comment.content,
                'cnt': cnt
            }
            return JsonResponse(context)
        return redirect('community:detail', review.pk)
    return redirect('accounts:login')


@require_POST
@login_required
def like(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        user = request.user

        if review.like_users.filter(pk=user.pk).exists():
            review.like_users.remove(user)
            liked = False

        else:
            review.like_users.add(user)
            liked = True

        context = {
            'liked': liked,
            'count': review.like_users.count()
        }
        return JsonResponse(context)
    return redirect('accounts:login')


def search(request):
    context = dict()
    free_reviews = Review.objects.all()
    review = request.POST.get('review', "")

    if review:
        free_reviews = free_reviews.filter(title__icontains=review)
        context['free_reviews'] = free_reviews
        context['review'] = review
        return render(request, 'community/search.html', context)

    else:
        return render(request, 'community/search.html')



def search_movie(request):
    free_movies = Movie.objects.all()
    movie = request.GET.get('movie')
    
    if movie:
        free_movies = free_movies.filter(title__icontains=movie)
        selected = []

        for free_movie in free_movies:
            selected.append(model_to_dict(free_movie, fields=['title', 'poster_path']))

    return JsonResponse({'status': 200, 'data': selected})

community/templates/community/_card.html
<section class="ftco-section ftco-no-pb" id="resume-section">
  <div class="container">
    <div class="row justify-content-center pb-5">
      <div class="col-md-10 heading-section text-center ftco-animate">
        <h1 class="big big-2">Review</h1>
        <h2 class="mb-4">Review</h2>
        {% comment %} <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p> {% endcomment %}
      </div>
    </div>
    <div class="row">
      {% for review in reviews %}
        <div class="col-md-6">
          <div class="resume-wrap ftco-animate">
            <span class="date">
              {% for j in "x"|rjust:'5' %}
                {% if forloop.counter0 < review.rank %}
                  <span>★</span>
                {% else %}
                  <span>☆</span>
                {% endif %}
              {% endfor %}
            </span>
            <a href="{% url 'community:detail' review.pk %}"><h2>{{ review.title }}</h2></a>
            <div>{{ review.user }}</div>
            <span class="position">{{ review.movie_title }}</span>
            <p class="mt-4" id="cutcontent">{{ review.content }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</section>

community/templates/community/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div class="container">
    <section class="ftco-section contact-section ftco-no-pb" id="contact-section">
      {% if request.resolver_match.url_name == 'create' %}
        <h1>CREATE</h1>
      {% elif request.resolver_match.url_name == 'update' %}
        <h1>UPDATE</h1>
      {% endif %}
      
      <div class="row no-gutters block-9">
        <div class="col-md-6 order-md-last d-flex">
          <form action="" method="POST" class="bg-light p-4 p-md-5 contact-form mb-0">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="fieldWrapper form-group">
              {{ form.title.errors }}
              <input type="text" class="form-control" placeholder="Title" required_id="id_title" name="title" value="{{ review.title }}">
            </div>
            <div class="fieldWrapper form-group">
                {{ form.movie_title.errors }}
                <div style="display: none;">{{ form.movie_title }}</div>
                  <div id="autocomplete" class="autocomplete">
                    <input class="autocomplete-input" name="movie" placeholder="Find Movie" style="width: 100%;" value="{{ review.movie_title }}"/>
                    <ul class="autocomplete-result-list" style="width: 100%;"></ul>
                </div>
            </div>
            <div class="fieldWrapper form-group">
                {{ form.rank.errors }}
                <label for="id_rank">Rank : </label>
                {{ form.rank }}
                {% include 'community/star_rate.html' %}
            </div>
            <div class="fieldWrapper form-group">
                {{ form.content.errors }}
                <textarea name="content" id="id_content" cols="30" rows="7" class="form-control" placeholder="Content" value="">{{ review.content }}</textarea>
            </div>
            
            <div class="form-group">
              <p><input type="submit" value="Send Review" class="btn btn-primary py-3 px-5"/></p>
            </div>
          </form>
          <hr>
        </div>        
        <div class="col-md-6 d-flex">
          <div id="selected-poster" class="img" style="background-image: url('http://image.tmdb.org/t/p/original{{review.movie_title.poster_path}}'); background-size: contain;"></div>
        </div>

      </div>
    </section>
    <a href="{% url 'community:index' %}">[back]</a>
  </div>


{% endblock content %}

{% block script %}
  <script>

  function selected_poster(path) {
    const poster = document.querySelector('#selected-poster')

    poster.style = `background-image: url("http://image.tmdb.org/t/p/original${path}"); background-size: contain;`

  }



  function fn_selTest( val )
  {
    var ele = document.getElementById('id_movie_title');

    for( i=0,j=ele.length; i<j; i++ )
    {
      if( ele.options[i].innerText == val )
      {
        ele.options[i].selected = true;
        ele.options[i].innerText = val
        break;
      }
    }
  }

    new Autocomplete('#autocomplete', {

      search : input => {
        const url = `/community/search-movie/?movie=${input}`
        return new Promise(resolve => {
          if (input.length < 2) {
            return resolve([])
          }
          fetch(url)
          .then(response => response.json())
          .then(response => {
            resolve(response.data)
          })
        })
      },
      renderResult: (result, props) => `
        <li ${props}>
          <span class="wiki-snippet">
            <img src="http://image.tmdb.org/t/p/original/${result.poster_path}" style="width: 10%;">
          </span>
          <span class="wiki-title">
          ${result.title}
          </span>
        </li>
      `,

      getResultValue: result => result.title,

      onSubmit : result => {
        console.log(result.title)
        fn_selTest(result.title)
        selected_poster(result.poster_path)
      }
    })

  </script>

{% endblock script %}

community/templates/community/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load mathfilters %}

{% block addcss %}
  <style>
    #id_content {
      height: 50px;
    }

    #review-content {
      word-break: break-all;
    }
  </style>

{% endblock addcss %}


{% block content %}
<div style="background-image: linear-gradient(rgba(0, 0, 0, 0.2), rgba(255, 255, 255, 0.2));">
  <div class="container">
    <div class="row px-5">
      <div class="col-6 px-0">
        <hr>
        <a href="{% url 'accounts:profile' review.user %}"><h1>{{ review.user }}님의</h1></a>
        <h2>{{ review.movie_title }} 리뷰</h2>
        <h5>{{ review.title }}</h5>
        <hr>
        <div id="review-content">
          {{ review.content }}
        </div>
        <hr>
        <span>별점 : </span>
        {% for j in "x"|rjust:'5' %}
          {% if forloop.counter0 < review.rank %}
            <span>★</span>
          {% else %}
            <span>☆</span>
          {% endif %}
        {% endfor %}
        <div>
          {% if user in review.like_users.all %}
            <i data-review-pk="{{ review.pk }}" class="fas fa-heart" style="color: red"></i>
          {% else %}
            <i data-review-pk="{{ review.pk }}" class="far fa-heart" style="color: black"></i>
          {% endif %}
          <span id="like-count-{{ review.pk }}">{{ review.like_users.all|length }}</span>명이 좋아합니다.
          <hr>
          <div class="d-flex">
            <form action="{% url 'community:update' review.pk %}">
              <button class="btn btn-outline-light" id="update-btn">수정</button>
            </form>
            <form action="{% url 'community:delete' review.pk %}" class="ml-2" method="POST">
              {% csrf_token %}
              <button class="btn btn-outline-danger" id="delete-btn" data-review-user="{{ review.user }}">삭제</button>
            </form>
          </div>
        
        </div>

        <h4>comment</h4>
        <div id="comment-area">
          {% if comments|length %}
            <p id="cnt-comment"><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
          {% endif %}
          {% for comment in comments %}
            <div>
              {{ comment.user }} - {{ comment.content }}
            </div>
          {% empty %}
            <p id="cnt-comment"><b>댓글이 없어요..</b></p>
          {% endfor %}
        </div>
          <hr>
        <form class="d-flex justufy-content-start" method="POST" id="comment-form" data-review-pk="{{ review.pk }}">
          {% csrf_token %}
          <div class="my-auto p-2">
            <textarea name="content" id="id_content" cols="40" rows="10"></textarea>
          </div>
          <p class="mt-3"><input type="submit" class="btn btn-white btn-outline-white" value="등록"></p>
        </form>
      </div>
      
      <div class="col-6 mt-5">
        <a href="{% url 'movies:detail' review.movie_title.pk %}"><img src="http://image.tmdb.org/t/p/original/{{ review.movie_title.poster_path }}" alt="" width="100%;"></a>
      </div>

    </div>
    
  </div>

</div>

{% endblock content %}

{% block script %}



  <script>
  
  const deleteBtn = document.querySelector('#delete-btn')
  const user = document.querySelector('#user-status').getAttribute('data-value')

  deleteBtn.addEventListener('click', (event) => {

        if ( user === "AnonymousUser" ) {
          alert('로그인이 필요합니다!')
        } else if ( user != deleteBtn.getAttribute('data-review-user') ) {
          alert('권한이 없습니다.')
        }
      })

  
  </script>

  <script>
  
    const updateBtn = document.querySelector('#update-btn')

    updateBtn.addEventListener('click', (event) => {

          if ( user === "AnonymousUser" ) {
            alert('로그인이 필요합니다!')
          } else if ( user != deleteBtn.getAttribute('data-review-user') ) {
            alert('권한이 없습니다.')
          }
        })

  
  </script>
  <script>
    const hearts = document.querySelectorAll('.fa-heart')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value    

    hearts.forEach((heart) => {
      heart.addEventListener('click', (event) => {
        const userInput = document.querySelector('#id_content')
        console.log(userInput.value)
        userInput.value = ""

        const reviewPk = event.target.dataset.reviewPk
        if ( user === "AnonymousUser") {
          alert('로그인이 필요합니다!')
        } else {
        axios.post(`/community/${reviewPk}/like/`, {}, {
          headers: {'X-CSRFToken': csrftoken}
        })
          .then((res) => {

            if (res.data.liked) {
              event.target.style.color = 'red'
            } else {
              event.target.style.color = 'black'
            }
            event.target.classList.toggle('fas')
            event.target.classList.toggle('far')

            const likeSpan = document.querySelector(`#like-count-${reviewPk}`)
            likeSpan.innerText = res.data.count
          })
        }
      })
    })
  </script>
    
  <script>
    const commentForm = document.querySelector('#comment-form')

    commentForm.addEventListener('submit', function (event) {
      event.preventDefault()

      if ( user === "AnonymousUser") {
        const userInput = document.querySelector('#id_content')
        userInput.value = ""
        alert('로그인이 필요합니다!')
      } else {
        const content = document.querySelector('#id_content').value     
        const reviewPk = event.target.dataset.reviewPk
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

        const formData = new FormData()
        formData.append('content', content)
        
        axios({
          method: 'post',
          url: `/community/${reviewPk}/comments/create/`,
          data: formData,
          headers: {'X-CSRFToken': csrftoken}
        })
          .then((res) => {
            const commentArea = document.querySelector('#comment-area')
            const cntComment = document.querySelector('#cnt-comment')
            const div = document.createElement('div')
            const mb = document.createElement('b')

            if (commentArea.innerText == "댓글이 없어요..") {
              const p = document.querySelector('#cnt-comment')
              p.innerText = ""
            }
            
            cntComment.innerText = ""
            mb.innerText = `${res.data.cnt}개의 댓글이 있습니다.`
            cntComment.appendChild(mb)

            div.innerText = `${res.data.username} - ${res.data.content}`
            commentArea.appendChild(div)

            event.target.reset()
          })
      }
    })
  
  </script>

{% endblock script %}

community/templates/community/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}

{% block script %}
  <style>
    #cutcontent {
      display: inline-block;
      white-space: nowrap;
      overflow: hidden; 
      text-overflow: ellipsis;
      /* 여러 줄 자르기 추가 스타일 */ 
      white-space: normal; 
      line-height: 1.2; 
      height: 3.6em; 
      word-wrap: break-word; 
      display: -webkit-box; 
      -webkit-line-clamp: 3; 
      -webkit-box-orient: vertical;
    }

    #pagenation > ul > li > a {
      background-color: black;
      border-color: #999999;
      border-width: medium;
      color: hsl(40, 90%, 60%);
    }
  
  </style>

{% endblock script %}


{% block content %}
  {% include 'community/_card.html' %}

  <div class="d-flex justify-content-center" id="pagenation">
      {% bootstrap_pagination reviews %}
  </div>
  <div class="container d-flex justify-content-between pb-2">
    <form class="my-auto" action="{% url 'community:search' %}" method="POST">
      {% csrf_token %}
      <input type="search" placeholder="검색어를 입력해주세요." aria-label="Search" name="review", value="{{review}}">
      <button type="submit" class="btn btn-white btn-outline-white">검색</button>
    </form>
    <form action="{% url 'community:create' %}">
      <button id="write-comment" class="btn btn-primary my-auto">작성</button>
    </form>
  </div>
{% endblock content %}

community/templates/community/search.html
{% extends 'base.html' %}

{% block script %}
  <style>
    #cutcontent {
      display: inline-block;
      white-space: nowrap;
      overflow: hidden; 
      text-overflow: ellipsis;
      /* 여러 줄 자르기 추가 스타일 */ 
      white-space: normal; 
      line-height: 1.2; 
      height: 3.6em; 
      word-wrap: break-word; 
      display: -webkit-box; 
      -webkit-line-clamp: 3; 
      -webkit-box-orient: vertical;
    }
  </style>

{% endblock script %}


{% block content %}
  <section class="ftco-section ftco-no-pb" id="resume-section">
    <div class="container">
      <div class="row justify-content-center pb-5">
        <div class="col-md-10 heading-section text-center ftco-animate">
          <h1 class="big big-2">Result</h1>
          <h2 class="mb-4">Result</h2>
          {% comment %} <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p> {% endcomment %}
        </div>
      </div>
      {% if not free_reviews %}
        <h2>검색 결과가 없습니다.</h2>

      {% else %}
        <div class="row">
          {% for review in free_reviews.all %}
            <div class="col-md-6">
              <div class="resume-wrap ftco-animate">
                <span class="date">
                  {% for j in "x"|rjust:'5' %}
                    {% if forloop.counter0 < review.rank %}
                      <span>★</span>
                    {% else %}
                      <span>☆</span>
                    {% endif %}
                  {% endfor %}
                </span>
                <a href="{% url 'community:detail' review.pk %}"><h2>{{ review.title }}</h2></a>
                <div><a href="{% url 'accounts:profile' review.user %}" style="color: white;">{{ review.user }}</a></div>
                <span class="position"><a href="{% url 'community:detail' review.pk %}" style="color: white;">{{ review.movie_title }}</a></span>
                <p class="mt-4" id="cutcontent">{{ review.content }}</p>
              </div>
            </div>
          {% endfor %}
        </div>  
      {% endif %}
    </div>
  </section>


  <div class="container d-flex justify-content-between pb-2">
    <form class="my-auto" action="{% url 'community:search' %}" method="POST">
      {% csrf_token %}
      <input type="search" placeholder="검색어를 입력해주세요." aria-label="Search" name="review", value="{{review}}">
      <button type="submit" class="btn btn-white btn-outline-white">검색</button>
    </form>
    <form action="{% url 'community:create' %}">
      <button id="write-comment" class="btn btn-primary my-auto">작성</button>
    </form>
  </div>
{% endblock content %}

community/templates/community/star_rate.html
{% load static %}

{% include "django/forms/widgets/input.html" %}

{% comment %} <link rel="stylesheet" href="{% static 'widgets/rateit.js-master/scripts/rateit.css' %}">
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script src="{% static 'widgets/rateit.js-master/scripts/jquery.rateit.min.js' %}" ></script> {% endcomment %}
{{ form.media }}
<div id="star_{{ widget.attrs.id }}" class="rateit" data-rateit-backingfld="#{{ widget.attrs.id }}"></div>
{% comment %} <input type="rating" name="grade" value="4" required="" id="id_grade" min="0" max="5" step="1" style="display: none;"> {% endcomment %}