accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('search-movie/', views.search_movie, name='search_movie'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like')

]

fluffyhappiness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('about/',  TemplateView.as_view(template_name="about.html"), name='about'),
    path('', views.home, name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('search-movie/', views.search_movie, name='search_movie'),
    path('api-movie/', views.api_movie),
    path('api-genre/', views.api_genre),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comments/create/', views.create_moviecomment, name='create_moviecomment'),
    path('<int:movie_pk>/watch/', views.watch, name='watch'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    image = ProcessedImageField(upload_to='avatars',
                                processors=[ResizeToFill(400, 400)],
                                format='JPEG',
                                options={'quality': 60}
            )


    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email', 'image')

accounts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm
from movies.models import CheckTime
from community.models import Review
import heapq

# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('accounts:profile', request.user.username)

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('accounts:login') # 회원가입 완료시 로그인 페이지로 이동
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }        
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('accounts:profile', request.user.username)

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'accounts:profile', request.user.username) # 홈화면으로 가도록 처리 필요
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

@login_required
def profile(request, username):
    profile_host = get_object_or_404(get_user_model(), username=username)
    host_movies = CheckTime.objects.filter(user_id=profile_host.pk)
    host_reviews = Review.objects.filter(user_id=profile_host.pk)
    most_genres = {}
    for movie in host_movies:
        tmp_genres = movie.movie.genres.all()
        for genre in tmp_genres:
            if not most_genres.get(genre.name, 0):
                most_genres[genre.name] = 1
            else:
                most_genres[genre.name] += 1
    most_genres = heapq.nlargest(3, most_genres, key=most_genres.get)

    context = {
        'profile_host': profile_host,
        'host_movies': host_movies,
        'host_reviews': host_reviews,
        'most_genres': most_genres,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        profile_host = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        if profile_host != user:
            if profile_host.followers.filter(pk=user.pk).exists():
                profile_host.followers.remove(user)
            else:
                profile_host.followers.add(user)
    return redirect('accounts:profile', profile_host.username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}

  <form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}

      <div class="resume-wrap ftco-animate row justify-content-center align-items-center">
          <div class="col-2">
            <h1 class="navbar-brand">Login</h1>
          </div>
          <div class="col-4">
            <span style="font-weight: 600; color: #fff;  width: 130px;">ID: {{ form.username }}</span>
          </div>
          <div class="col-4">
            <span style="font-weight: 600; color: #fff;  width: 130px;">PW: {{ form.password }}</span>
          </div>
          <div class="col-2">
            <input type="submit" value="login">
            <input type="hidden" name="next" value="{{ next }}">
          </div>
      </div>
    
  </form>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  {% with followings=profile_host.followings.all followers=profile_host.followers.all %}
  <div class="container ftco-about img ftco-section ftco-no-pb">
    <div class="row d-flex">
      <div class="col-md-6 col-lg-5 d-flex">
        <div class="img-about img d-flex align-items-stretch">
          <div class="overlay"></div>
          <img src="{{ profile_host.image.url}}" style="border-radius: 50%" alt="">
          <div class="img d-flex align-self-stretch align-items-center">
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-7 pl-lg-5 pb-5">
        <div class="row justify-content-start pb-3">
          <div class="col-md-12 heading-section ftco-animate">
            <h1 class="big">{{ profile_host }}</h1>
            <h2 class="mb-4">{{ profile_host }}</h2>
            <div class="d-flex justify-content-between">
              <p class="placeholder-wave text-dark font-weight-bold">
                {% for genre in most_genres %}
                  <span class="placeholder px-3" style="color: #ffc107;">#{{ genre }}</span>
                {% endfor %}
              </p>
            </div>
            <ul class="about-info mt-4 px-md-0 px-2">
              <li class="d-flex"><span style="font-weight: 600; color: #fff;  width: 130px;">Movie watched:</span> <span>{{ host_movies | length }}</span></li>
              <li class="d-flex"><span style="font-weight: 600; color: #fff;  width: 130px;">Posted Reviews:</span> <span>{{ host_reviews | length }}</span></li>
              <li class="d-flex"><span style="font-weight: 600; color: #fff;  width: 130px;">flollowers:</span> <span>{{ followers|length }}</span></li>
              <li class="d-flex"><span style="font-weight: 600; color: #fff;  width: 130px;">flollowings:</span> <span>{{ followings|length }}</span></li>
            </ul>
          </div>
        </div>
        <div class="counter-wrap ftco-animate d-flex mt-md-3">
          {% if request.user != profile_host %}
            <div class="d-flex align-items-center">
              <form action="{% url 'accounts:follow' profile_host.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in followers %}
                  <button class="btn btn-primary py-3 px-3" id="followBtn">언팔로우</button>
                {% else %}
                  <button class="btn btn-primary py-3 px-3" id="followBtn">팔로우</button>

                {% endif %}
              </form>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="app">
      <div class="d-flex justify-content-around mt-5">
        <button id="movieBtn" type="button" class="btn btn-outline-warning active" @click="switchMovie">
          {{ user.username }}님의 영화들
        </button>
        <button id="reviewBtn" type="button" class="btn btn-outline-warning" @click="switchReview">
          {{ user.username }}님의 리뷰들
        </button>
      </div>
      {% comment %} 버튼을 누르면 나오는 영화/댓글 목록 {% endcomment %}
      <div class="tab-content">
        {% comment %} user 영화목록 {% endcomment %}
        <div class="tab-pane fade show active" id="user_movies" v-if="movies">
          <div class="row mt-5">
            {% for movie in host_movies %}
            <div class="col-md-3">
              <div class="project img ftco-animate d-flex justify-content-center align-items-center fadeInUp ftco-animated" style="background-image: url(http://image.tmdb.org/t/p/original/{{ movie.movie.poster_path }});">
                <div class="overlay"></div>
                <div class="text text-center p-4">
                  <img src="" alt="">
                  <h3><a href="{% url 'movies:detail' movie.movie.pk %}">{{ movie.movie }}</a></h3>
                  <span>{{ movie.check_time }}</span>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        {% comment %} user 리뷰 목록 {% endcomment %}
        <div class="tab-pane show active" id="user_reviews" v-if="reviews">
          <div class="row mt-5">
            {% for review in host_reviews %}
            <div class="col-md-3">
              <div class="project img ftco-animate d-flex justify-content-center align-items-center fadeInUp ftco-animated" style="background-image: url(http://image.tmdb.org/t/p/original/{{ review.movie_title.poster_path }});">
                <div class="overlay"></div>
                <div class="text text-center p-4">
                  <img src="" alt="">
                  <h3><a href="{% url 'community:detail' review.pk %}">{{ review.title }}</a></h3>
                  <span>{{ review.movie_title }}</span>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endwith %}
{% endblock content %}

{% block script %}
  <script>
    const app = new Vue({
      el: '.app',
      data: {
        movies: true,
        reviews: false,
      },
      methods: {
        switchMovie: function () {
          const movieBtn = document.querySelector('#movieBtn')
          const reviewBtn = document.querySelector('#reviewBtn')
          movieBtn.classList.add('active')
          reviewBtn.classList.remove('active')
          this.movies = true
          this.reviews = false
        },
        switchReview: function () {
          const movieBtn = document.querySelector('#movieBtn')
          const reviewBtn = document.querySelector('#reviewBtn')
          movieBtn.classList.remove('active')
          reviewBtn.classList.add('active')
          this.movies = false
          this.reviews = true
        }
      },
    })
  </script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="d-flex">
      <div class="col-md-6 col-lg-7 pl-lg-5 pb-5">
        <div class="row justify-content-start pb-3">
          <div class="col-md-12 heading-section ftco-animate fadeInUp ftco-animated">
            <div class="col-6 ml-auto mt-5">
              <h2 class="mb-4">Signup</h2>
              <p>가입정보를 입력해주세요</p>
              <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <ul class="about-info mt-4 px-md-0 px-2">
                  <li class="d-flex"><span>ID:</span></li>
                  <li class="d-flex">{{ form.username }}</li>
                  <li class="d-flex"><span>PW:</span></li>
                  <li class="d-flex">{{ form.password1 }}</li>
                  <li class="d-flex"><span>PW CHECK:</span></li>
                  <li class="d-flex">{{ form.password2 }}</li>
                  <li class="d-flex"><span>E-mail:</span></li>
                  <li class="d-flex">{{ form.email }}</li>
                  <li class="d-flex"><span>PROFILE IMAGE:</span></li>
                  <li class="d-flex btn btn-outline-light btn-sm">{{ form.image }}</li>
                </ul>
                <input class="btn btn-outline-warning" style="float: right;" type="submit">
              </form>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock content %}