accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('search/', views.search, name='search'),
    path('search-movie/', views.search_movie, name='search_movie'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/like/', views.like, name='like')

]

fluffyhappiness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from movies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('about/',  TemplateView.as_view(template_name="about.html"), name='about'),
    path('', views.home, name='home')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('search-movie/', views.search_movie, name='search_movie'),
    path('api-movie/', views.api_movie),
    path('api-genre/', views.api_genre),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comments/create/', views.create_moviecomment, name='create_moviecomment'),
    path('<int:movie_pk>/watch/', views.watch, name='watch'),
]

templates/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark ftco-navbar ftco-navbar-light site-navbar-target pt-0" id="ftco-navbar" style="position: sticky;">
	    <div class="container" style="background-color: black; opacity: 0.7;">
	      <a class="navbar-brand" href="{% url 'movies:home' %}" data-value="{{ user }}" id="user-status">{Fluffy-Happiness}</a> 
        {% comment %} home 화면으로 가도록 하이퍼링크 {% endcomment %}
        {% if user.is_authenticated %}
        <div>Welcome <a href="{% url 'accounts:profile' user.username %}">{{ user }}</a>!</div>

				<div class="d-flex">
					<form class="my-auto" action="{% url 'accounts:logout' %}" method="POST" id="logout-form">
						{% csrf_token %}
						<a href="#" onclick="document.querySelector('#logout-form').submit()">logout</a>
					</form>
				</div>
        {% else %}
        <div><a href="{% url 'accounts:signup'%}">signup</a></div>
        <div><a href="{% url 'accounts:login' %}">login</a></div>
        {% endif %}
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav" style="flex-grow: 0.5;">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="{% url 'movies:home' %}" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="{% url 'about' %}" class="nav-link"><span>About</span></a></li>
	          <li class="nav-item"><a href="{% url 'movies:index' %}" class="nav-link"><span>Movie</span></a></li>
	          <li class="nav-item"><a href="{% url 'community:index' %}" class="nav-link"><span>Review</span></a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>

templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center mb-5 pb-3">
    <div class="col-md-7 heading-section text-center ftco-animate fadeInUp ftco-animated">
      <h1 class="big big-2">FLUFFY &nbsp HAPPINESS </h1>
      <h2 class="mb-4">About us</h2>
      <p>Samsung Software Academy For Youth 6th, Final PJT</p>
    </div>
  </div>
  <div class="row d-flex contact-info my-5 justify-content-center">
    <div class="col-md-6 col-lg-3 d-flex ftco-animate fadeInUp ftco-animated">
      <div class="align-self-stretch box p-4 text-center">
        <div class="icon d-flex align-items-center justify-content-center">
          <span class="icon-github"></span>
        </div>
        <h3 class="mb-4">Github</h3>
        <a href="https://github.com/FallingStar624/fluffy-happiness">PJT: FLUFFY-HAPPINESS</a>
      </div>
    </div>

    <div class="col-md-6 col-lg-3 d-flex ftco-animate fadeInUp ftco-animated">
      <div class="align-self-stretch box p-4 text-center">
        <div class="icon d-flex align-items-center justify-content-center">
          <span class="icon-paper-plane"></span>
        </div>
        <h3 class="mb-4">E-mail address</h3>
        <p><a href="mailto:pairy624@gmail.com">pairy624@gmail.com</a></p>
        <p><a href="mailto:ks94love@gmail.com">ks94love@gmail.com</a></p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/base.html
  {% load static %}
  <head>
    {% block startscript %}
    
    {% endblock startscript %}
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{Fluffy Happiness}</title>
    <link rel="stylesheet" href={% static 'css/open-iconic-bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'css/animate.css' %}>
    <link rel="stylesheet" href={% static 'css/owl.carousel.min.css' %}>
    <link rel="stylesheet" href={% static 'css/owl.theme.default.min.css' %}>
    <link rel="stylesheet" href={% static 'css/magnific-popup.css' %}>
    <link rel="stylesheet" href={% static 'css/aos.css' %}>
    <link rel="stylesheet" href={% static 'css/ionicons.min.css' %}>
    <link rel="stylesheet" href={% static 'css/flaticon.css' %}>
    <link rel="stylesheet" href={% static 'css/icomoon.css' %}>
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href="{% static 'css/autocomplete-js-dist-style.css' %}"/>


    {% block addcss %}
    {% endblock addcss %}

  </head>
  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    {% include '_nav.html' %}
    


    {% block content %}
    {% endblock %}
    <script src="https://kit.fontawesome.com/e87731a046.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
    <script src={% static 'js/jquery.min.js' %}></script>
    <script src={% static 'js/jquery-migrate-3.0.1.min.js' %}></script>
    <script src={% static 'js/popper.min.js' %}></script>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    <script src={% static 'js/jquery.easing.1.3.js' %}></script>
    <script src={% static 'js/jquery.waypoints.min.js' %}></script>
    <script src={% static 'js/jquery.stellar.min.js' %}></script>
    <script src={% static 'js/owl.carousel.min.js' %}></script>
    <script src={% static 'js/jquery.magnific-popup.min.js' %}></script>
    <script src={% static 'js/aos.js' %}></script>
    <script src={% static 'js/jquery.animateNumber.min.js' %}></script>
    <script src={% static 'js/scrollax.min.js' %}></script>
    <script src={% static 'js/main.js' %}></script>

    <!-- Vue CDN -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    
    {% block script %}
    {% endblock script %}
  </body>
</html>